BloodWindow\BWBundle\Entity\Work:
    type: entity
    table: wip
    repositoryClass: BloodWindow\BWBundle\Entity\WorkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: '100'
        anio:
            type: integer
        director:
            type: string
            length: '100'
        pais:
            type: string
            length: '100'
        compania:
            type: string
            length: '100'
        estado:
            type: string
            length: '50'
        duracion:
            type: integer
        cargo:
            type: string
            length: '4000'
        sinopsisEspaniol:
            type: string
            length: '4000'
        sinopsisIngles:
            type: string
            length: '4000'
        metas:
            type: string
            length: '4000'
        email:
            type: string
            length: '4000'
        telefono:
            type: integer
        urlVideo:
            type: string
            length: '4000'    
    lifecycleCallbacks: {  }
