blood_window_bw_homepage:
    path:     /
    defaults: { _controller: BloodWindowBWBundle:Default:index }

BloodWindowBWBundle_admin:
    path:     /admin
    defaults: { _controller: BloodWindowBWBundle:Corto:index }

BloodWindowBWBundle_admin_corto:
    resource: "@BloodWindowBWBundle/Resources/config/routing/corto.yml"
    prefix: /admin/corto

BloodWindowBWBundle_admin_festival:
    resource: "@BloodWindowBWBundle/Resources/config/routing/festival.yml"
    prefix:   /admin/festival

BloodWindowBWBundle_admin_genero:
    resource: "@BloodWindowBWBundle/Resources/config/routing/genero.yml"
    prefix:   /admin/genero

BloodWindowBWBundle_admin_proyecto:
    resource: "@BloodWindowBWBundle/Resources/config/routing/proyecto.yml"
    prefix:   /admin/proyecto

BloodWindowBWBundle_admin_work:
     resource: "@BloodWindowBWBundle/Resources/config/routing/work.yml"
     prefix:   /admin/work

BloodWindowBWBundle_corto:
    path:     /corto
    defaults: { _controller: BloodWindowBWBundle:Default:detalleCorto }

BloodWindowBWBundle_filtrar:
    path:     /buscar/corto
    defaults: { _controller: BloodWindowBWBundle:Default:obtenerCortos }

BloodWindowBWBundle_carousel:
    path:     /buscar/corto/carousel
    defaults: { _controller: BloodWindowBWBundle:Default:obtenerCortosCarousel }

BloodWindowBWBundle_obtener_festivales:
    path:     /buscar/festival
    defaults: { _controller: BloodWindowBWBundle:Default:obtenerFestivales }

BloodWindowBWBundle_obtener_generos:
    path:     /buscar/genero
    defaults: { _controller: BloodWindowBWBundle:Default:obtenerGeneros }

BloodWindowBWBundle_detalle_work:
    path:     /industria/work
    defaults: { _controller: BloodWindowBWBundle:Work:obtenerDetalleWork }

BloodWindowBWBundle_obtener_works:
    path:     /industria/works
    defaults: { _controller: BloodWindowBWBundle:Work:obtenerWorks }

BloodWindowBWBundle_detalle_proyecto:
    path:     /industria/proyecto
    defaults: { _controller: BloodWindowBWBundle:Proyecto:obtenerDetalleProyecto }

BloodWindowBWBundle_obtener_proyectos:
    path:     /industria/proyectos
    defaults: { _controller: BloodWindowBWBundle:Proyecto:obtenerProyectos }

admin_corto_upload_carousel_pic:
    path:     /buscar/usuario
    defaults: { _controller: "BloodWindowBWBundle:Default:obtenerUsuario" }
    requirements: { _method: post }