blood_window_bw_homepage:
    path:     /
    defaults: { _controller: BloodWindowBWBundle:Default:index }

BloodWindowBWBundle_admin_corto:
    resource: "@BloodWindowBWBundle/Resources/config/routing/corto.yml"
    prefix: /admin/corto

BloodWindowBWBundle_corto:
    path:     /corto
    defaults: { _controller: BloodWindowBWBundle:Default:detalleCorto }

BloodWindowBWBundle_filtrar:
    path:     /buscar/corto
    defaults: { _controller: BloodWindowBWBundle:Default:obtenerCortos }