<?php

namespace BloodWindow\BWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CortoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CortoRepository extends EntityRepository
{
}
