<?php

namespace BloodWindow\BWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalRepository extends EntityRepository
{
}
